version: '3.7'

services:
  bot0:
    build: .
    restart: unless-stopped
    ports:
      - "8081:8081/tcp"
    volumes:
      - ./bot0/logs:/app/ProfitTrailer/logs/
      - ./bot0/data:/app/ProfitTrailer/data/
